config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :staff_users
    resources :users
    resources :drinks
    resources :volumes
    resources :drinks_volumes
    resources :drink_additions
    resources :coffee_shops
    resources :drink_categories
    resources :settings, only: %i(edit update index show)
    resources :payments, only: %i(index show)
    resources :orders, only: %i(index show)

    root to: "drinks#index"
  end

  devise_for :admin_users, skip: [:registrations]
  devise_for :staff_users, skip: [:registrations]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :staff do
    resources :orders, only: :index
    resource :prepare_drink, only: :create
    resource :break, only: :create, controller: :break
    resource :notification_tokens, only: :create

    root to: "orders#index"
  end

  namespace :api do
    mount_devise_token_auth_for "User", at: "auth"
    namespace :v1 do
      resources :drinks, only: :index, defaults: { format: :json }
      resources :drink_additions, only: :index, defaults: { format: :json }
      resources :coffee_shops, only: :index, defaults: { format: :json }
      resources :orders, only: %i(index show create), defaults: { format: :json }
      resources :payment_cards, only: %i(index destroy), defaults: { format: :json }
      resources :drink_categories, only: :index, defaults: { format: :json }
    end
  end

  resource :payments, only: :create

  get "/", :to => redirect('/about-us.html')
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee_shop.rb
class CoffeeShop < ApplicationRecord
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :drink_category
  has_many :drinks_volumes, dependent: :destroy
  has_many :volumes, through: :drinks_volumes

  mount_uploader :coffee_image, ::CoffeeImageUploader
end

app/models/drink_addition.rb
class DrinkAddition < ApplicationRecord
end

app/models/drink_category.rb
class DrinkCategory < ApplicationRecord
  has_many :drinks
end

app/models/drinks_volume.rb
class DrinksVolume < ApplicationRecord
  belongs_to :drink
  belongs_to :volume
end

app/models/order.rb
class Order < ApplicationRecord
  has_paper_trail
  enum status: { draft: "draft", paid: "paid", prepared: "prepared" }

  belongs_to :drinks_volume
  belongs_to :user
  has_many :orders_additions
  has_many :drink_additions, through: :orders_additions
  has_one :payment
end

app/models/orders_addition.rb
class OrdersAddition < ApplicationRecord
  belongs_to :order
  belongs_to :drink_addition
end

app/models/payment.rb
class Payment < ApplicationRecord
  has_paper_trail

  belongs_to :order
end

app/models/payment_card.rb
class PaymentCard < ApplicationRecord
  has_paper_trail

  belongs_to :user

  scope :active, -> { where(deleted: [false, nil]) }
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/staff_user.rb
class StaffUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/stuff_user.rb
class StuffUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  include DeviseTokenAuth::Concerns::User

  has_many :orders
  has_many :payment_cards
end

app/models/volume.rb
class Volume < ApplicationRecord
  has_many :drinks_volumes
  has_many :drinks, through: :drinks_volumes
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :json, :html
end

app/controllers/payments_controller.rb
class PaymentsController < ::ApplicationController
  def create
    PaymentProcessor.new(params).process
    render json: { status: 200 }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fields/carrierwave_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

app/views/fields/carrierwave_field/_index.html.erb
<% if field.thumb.present? %>
  <%= image_tag field.thumb %>
<% end %>

app/views/fields/carrierwave_field/_show.html.erb
<% if field.url.present? %>
  <%= image_tag field.url %>
<% end %>

app/views/layouts/_firebase_notifications.html.erb
<script src="https://www.gstatic.com/firebasejs/4.12.1/firebase.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.12.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.12.0/firebase-messaging.js"></script>
<script>
  var config = {
    apiKey: "AIzaSyDNSBMp3qGRcHozMiKk_IhhXQzyXEwKGyo",
    authDomain: "nicecoffee-57e78.firebaseapp.com",
    databaseURL: "https://nicecoffee-57e78.firebaseio.com",
    projectId: "nicecoffee-57e78",
    storageBucket: "",
    messagingSenderId: "978135584480"
  };
  firebase.initializeApp(config);

  const messaging = firebase.messaging();
  messaging.usePublicVapidKey("BPC85ILQOaKObrR6_mXbEAiPWAFB-tWPj5LJfeIx6IDtcwbk2MfjRaZrJmux71fyKGO4VaSYhroXzsvErQpzjU0");

  if('Notification' in window) {
    subscribe();
  }

  function subscribe() {
    messaging.requestPermission()
      .then(function () {
        messaging.getToken()
          .then(function (currentToken) {
            if (currentToken) {
              sendTokenToServer(currentToken);
            } else {
              console.warn('Не удалось получить токен.');
              setTokenSentToServer(false);
            }
          })
          .catch(function (error) {
            console.warn('При получении токена произошла ошибка.', error);
            setTokenSentToServer(false);
          });
          messaging.onMessage(function(payload) {
            console.log('Message received. ', payload);
            new Notification(payload.notification.title, payload.notification);
          });
      })
      .catch(function (error) {
        console.warn('Не удалось получить разрешение на показ уведомлений.', error);
      });
  }

  function sendTokenToServer(currentToken) {
    if (!isTokenSentToServer(currentToken)) {
      console.log('Отправка токена на сервер...');

      $.post('<%= staff_notification_tokens_url %>', { notification_token: currentToken });
      setTokenSentToServer(currentToken);
      } else {
        console.log('Токен уже отправлен на сервер.');
      }
  }

  function isTokenSentToServer(currentToken) {
    return window.localStorage.getItem('sentFirebaseMessagingToken') == currentToken;
  }

  function setTokenSentToServer(currentToken) {
    window.localStorage.setItem('sentFirebaseMessagingToken', currentToken ? currentToken : '');
  }
</script>

app/views/layouts/_pusher.html.erb
<script src="https://js.pusher.com/4.1/pusher.min.js"></script>
<script>

  // Enable pusher logging - don't include this in production
  Pusher.logToConsole = true;

  var pusher = new Pusher('<%= ENV["PUSHER_KEY"]%>', {
    cluster: '<%= ENV["PUSHER_CLUSTER"]%>',
    encrypted: true
  });

  var channel = pusher.subscribe('coffee');
  channel.bind('ordered', function(data) {
    $(".js-orders-table").append(data)
  });
</script>

app/views/layouts/administrate/application.html.erb
<%#
# Application Layout

This view template is used as the layout
for every page that Administrate generates.

By default, it renders:
- Navigation
- Content for a search bar
  (if provided by a `content_for` block in a nested page)
- Flashes
- Links to stylesheets and JavaScripts
%>

<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="ROBOTS" content="NOODP">
  <meta name="viewport" content="initial-scale=1">
  <title>
    <%= content_for(:title) %> - <%= Rails.application.class.parent_name.titlecase %>
  </title>
  <%= render "stylesheet" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <% if current_admin_user.present? %>
      <div class="pull-right"><%= link_to "Выйти", destroy_admin_user_session_path, method: :delete %></div>
    <% end %>
  </div>
  <%= render "icons" %>

  <div class="app-container">
    <%= render "navigation" -%>

    <main class="main-content" role="main">
      <%= render "flashes" -%>
      <%= yield %>
    </main>
  </div>

  <%= render "javascript" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeBack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <% if current_admin_user.present? %>
        <div class="float-right"><%= link_to "Выйти", destroy_admin_user_session_path, method: :delete %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/staff.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeBack</title>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <% if current_staff_user.present? %>
        <div class="float-right"><%= link_to "Выйти", destroy_staff_user_session_path, method: :delete %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>

  <%= render "layouts/firebase_notifications" %>
  <%= render "layouts/pusher" %>
</html>